# Generated by Django 3.2.12 on 2022-07-29 17:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0025_auto_20220728_1930'),
        ('payments', '0003_bank_bankaccount_wallettransaction_withdrawalrequests'),
    ]

    operations = [
        migrations.CreateModel(
            name='FarmerSettlement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PENDING', 'PENDING'), ('FAILED', 'FAILED'), ('SETTLED', 'SETTLED')], default='PENDING', max_length=20)),
                ('updated', models.DateTimeField(auto_now_add=True)),
                ('success_timestamp', models.DateTimeField(blank=True, null=True)),
                ('purchase', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.purchase')),
            ],
        ),
    ]
