# Generated by Django 3.2.12 on 2022-06-08 06:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='channel',
            name='name',
        ),
    ]
