# Generated by Django 3.2.12 on 2022-06-08 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_remove_channel_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='TempChatFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='speeches')),
                ('timestamp', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
