# Generated by Django 3.2.12 on 2022-06-08 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_tempchatfile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tempchatfile',
            name='file',
            field=models.FileField(upload_to=''),
        ),
    ]
