# Generated by Django 4.0.4 on 2022-06-01 06:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_farm'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='farm',
            options={'ordering': ['name']},
        ),
    ]
