# Generated by Django 3.2.12 on 2022-07-22 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_contactmessage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='surname',
            new_name='last_name',
        ),
        migrations.AddField(
            model_name='user',
            name='first_name',
            field=models.CharField(default='PalmFarms', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='profile_pic',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('DISPATCHER', 'DISPATCHER'), ('RETAILER', 'RETAILER'), ('FARMER', 'FARMER')], max_length=200),
        ),
    ]
