# Generated by Django 3.2.12 on 2022-07-23 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_bank_bankaccount_wallettransaction_withdrawalrequests'),
        ('accounts', '0008_user_wallet'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='bank_accounts',
            field=models.ManyToManyField(blank=True, to='payments.BankAccount'),
        ),
    ]
