# Generated by Django 3.2.12 on 2022-07-28 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_user_bank_accounts'),
    ]

    operations = [
        migrations.AddField(
            model_name='farm',
            name='total_sales',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='farm',
            name='views',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
