# Generated by Django 3.2.12 on 2022-07-29 00:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_newslettermember'),
    ]

    operations = [
        migrations.CreateModel(
            name='FarmView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('viewed_time', models.DateTimeField(auto_now=True)),
                ('farm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.farm')),
            ],
        ),
    ]
