# Generated by Django 3.2.12 on 2022-06-03 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_cart_farmer'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='ordered_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
