# Generated by Django 3.2.12 on 2022-06-03 21:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_alter_cart_user'),
        ('products', '0012_cart_ordered_date'),
    ]

    operations = [
    ]
