# Generated by Django 3.2.12 on 2022-06-05 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0013_merge_0012_alter_cart_user_0012_cart_ordered_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='reference',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
