# Generated by Django 3.2.12 on 2022-07-23 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0017_product_tag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='tag',
            field=models.CharField(default='ddd', max_length=100, unique=True),
            preserve_default=False,
        ),
    ]
