# Generated by Django 3.2.12 on 2022-07-24 13:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0020_auto_20220724_1339'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coupon',
            name='single_use',
        ),
    ]
