# Generated by Django 3.2.12 on 2022-07-28 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0023_auto_20220726_0052'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='start_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
