# Generated by Django 3.2.12 on 2022-07-28 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0024_product_start_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='start_date',
        ),
        migrations.AddField(
            model_name='product',
            name='created',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
